GET http://localhost:3600/ 

###

GET http://localhost:3600/book 

###

POST http://localhost:3600/register
Content-Type: application/json

{
    "email": "rockashfaq@outlook.com",
    "password":"Ashfaq123",
    "name":"Ashfaqur Rahman"
}

###

POST http://localhost:3600/login
Content-Type: application/json

{
    "email": "rockashfaq0@outlook.com",
    "password":"Ashfaq123"
}

###

GET http://localhost:3600/logout
Content-Type: application/json

###

POST http://localhost:3600/file
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="uploadedFile"; filename="api_test.rest"


< ./api_test.rest
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

GET http://localhost:3600/file

###

GET http://localhost:3600/file/file_rockashfaq0@outlook.com_api_test.rest